### ISSUE TITLE
MailHog needed in the Xenial branch to catch outgoing emails

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/vdd#33]
We're missing mailcatcher in the xenial branch

**Comment by ghost** [comment]
Had some problems with MailCatcher - the script that was already there should have just worked but was failing due to some Ruby dependency. I tried to install Ruby as part of the install (which I didn't like as it was another dependency bloating the box) but this then broken MySQL for reasons I got tired of trying to debug.

In the end I had a look at DrupalVM which uses MailHog which describes itself as _MailCatcher but easier to install_ which sounded like a win. 

After destroying the vagrant box and starting again this time with MailHog instead of MailCatcher everything worked like a charm.

Just finishing testing then commit will appear below ...

**Comment by ghost** [comment]
Ref: https://github.com/mailhog/MailHog
